#app_lucky_number:
#  path: /lucky/number
#  controller: App\Controller\LuckyController::number

#controllers:
#  resource: '../src/Controller/'
#  type:     annotation

index:
  path: /
  controller: App\Controller\ProductController::index

create:
  path: /create
  controller: App\Controller\ProductController::create

