#app_lucky_number:
#  path: /lucky/number
#  controller: App\Controller\LuckyController::number

#controllers:
#  resource: '../src/Controller/'
#  type:     annotation

index:
  path: /
  controller: App\Controller\ProductController::index

create:
  path: /create
  controller: App\Controller\ProductController::create

createUser:
  path: /createuser
  controller: App\Controller\ProductController::createUser


product:
  path: /product
  controller: App\Controller\ProductController::product

show:
  path: /product/{id}
  controller: App\Controller\ProductController::show