#controllers:
#  resource: '../src/Controller/'
#  type:     annotation

index:
  path: /
  controller: App\Controller\ProductController::index

productCreate:
  path: /product/create
  controller: App\Controller\ProductController::create

productList:
  path: /product
  controller: App\Controller\ProductController::index

userRegister:
  path: /user/register
  controller: App\Controller\UserController::register

userFavoriteProduct:
  path: /user/favorite/product/{id}
  controller: App\Controller\UserController::favoriteProduct

userIndex:
  path: /user/
  controller: App\Controller\UserController::index

userFavoriteUser:
  path: /user/favorite/user/{id}
  controller: App\Controller\UserController::favoriteUser


userFavoriteUserDelete:
  path: /user/favorite/user/delete/{idUser}/{idFavoriteUser}
  controller: App\Controller\UserController::favoriteUserDelete

userLikeUser:
    path: /user/like/user/{id}
    controller: App\Controller\UserController::likeUser

userLikeProduct:
    path: /user/like/product/{id}
    controller: App\Controller\UserController::likeProduct

